FROM node:14-slim

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./yarn.lock ./
COPY gene.csv /app/data

RUN yarn install

COPY . .

EXPOSE 5000

CMD [ "index.js", "politicians.csv" ]